package com.mapper.model;

import java.util.Date;

public class Store {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.id
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.name
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.quanlity
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    private Integer quanlity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.quantity
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    private String quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.price
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.time
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.id
     *
     * @return the value of store.id
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.id
     *
     * @param id the value for store.id
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.name
     *
     * @return the value of store.name
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.name
     *
     * @param name the value for store.name
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.quanlity
     *
     * @return the value of store.quanlity
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public Integer getQuanlity() {
        return quanlity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.quanlity
     *
     * @param quanlity the value for store.quanlity
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public void setQuanlity(Integer quanlity) {
        this.quanlity = quanlity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.quantity
     *
     * @return the value of store.quantity
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.quantity
     *
     * @param quantity the value for store.quantity
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.price
     *
     * @return the value of store.price
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.price
     *
     * @param price the value for store.price
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.time
     *
     * @return the value of store.time
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.time
     *
     * @param time the value for store.time
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }
}