package com.mapper.mappers;

import com.mapper.model.Store;
import com.mapper.model.StoreExample;
import java.util.List;

import com.mapper.model.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    long countByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    int deleteByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    int insert(Store row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    int insertSelective(Store row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    List<Store> selectByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    Store selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    int updateByExampleSelective(@Param("row") Store row, @Param("example") StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    int updateByExample(@Param("row") Store row, @Param("example") StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    int updateByPrimaryKeySelective(Store row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Tue Feb 22 13:19:55 ICT 2022
     */
    int updateByPrimaryKey(Store row);

}